# Runs mysql container + ttrss container
version: '2'
services:
  db:
    image:  sameersbn/mysql:latest
    # restart: always
    environment:
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=ttrss
  ttrss:
    build: .
    # restart: always
    ports:
      - "$TTRSS_PORT:80"
    environment:
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=ttrss
      - DB_HOST=db
      - DB_PORT=3306
      - SELF_URL_PATH=http://localhost/
    links:
      - db:db
